### ISSUE TITLE
Reports about crashes when starting cartridges

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/WhereYouGo#65]
While downloading is confirmed working by all beta testers, there are some reports about not being able to play cartridges. We did not actively change any code in this part, however due to the raised targetSDK I guess there might be new problems.

I am currently waiting to get some GC-codes where cartridges are problematic. I tried to start several and had no problem so far.

**Comment by Lineflyer** [comment]
While looking through several comments on FB and support mail, the problem seems to focus on Android 8.0.
It seems impossible to plaz any cartridge on those devices. You can load and start them, but selecting some actions lead to crashes.

I will try to collect more information about GC-codes, which functions fail and maybe traces.

**Comment by Lineflyer** [comment]
Cache: GC80GNY
Device: Samsung A5 – Android 8.0.0
WhereYouGo: 2020.03.08

User Note: Ich kann die Cartridge per App und per Browser herunterladen und speichern.

Auch der Start funktioniert wunderbar.

Die Startseiten erscheinen, die Einleitung und die ersten Seiten funktionieren tadellos.

Bei unseren WIG komme ich tadellos bis ins Hauptmenü des Cartridge, dann wenn ich auf Orte gehe stürzt der Player ab 

Gleiche Cartridge auf gleichem Gerät mit WhereYouGo 0.9.3 läuft.

**Comment by Lineflyer** [comment]
Cache: ?
Device: Samsung S7, Android 8
WhereYouGo: 2020.03.08

User Note:
Immer wenn ich auf "Orte", "Du siehst", "Inventar" oder "Aufgaben" klicke, bricht die App weg.

 

"Karte", "Standort" und "Speichern" geht problemlos und auch Dialoge beim Betreten einer Zone funktionieren. Zum Glück, denn dadurch konnte ich gestern einen WIG fertigspielen.

 Hier der Inhalt des error.log im GWC-Verzeichnis nach dem Absturz:

 

2020/03/16 17:36:00
[gui.activity.wherigo.ListZonesActivity] onCreate()
java.lang.IllegalStateException: Only fullscreen opaque activities can request orientation
    at android.app.Activity.onCreate(Activity.java:1038)
    at android.support.v4.app.SupportActivity.onCreate(ComponentActivity.java:75)
    at android.support.v4.app.FragmentActivity.onCreate(FragmentActivity.java:335)
    at menion.android.whereyougo.gui.extension.activity.CustomActivity.onCreate(CustomActivity.java:161)
    at menion.android.whereyougo.gui.activity.wherigo.ListVariousActivity.onCreate(ListVariousActivity.java:176)
    at android.app.Activity.performCreate(Activity.java:7183)
    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1220)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2910)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3032)
    at android.app.ActivityThread.-wrap11(Unknown Source:0)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1696)
    at android.os.Handler.dispatchMessage(Handler.java:105)
    at android.os.Looper.loop(Looper.java:164)
    at android.app.ActivityThread.main(ActivityThread.java:6944)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
2020/03/16 17:36:00
[UncaughtExceptionHandler] uncaughtException main
android.util.SuperNotCalledException: Activity {menion.android.whereyougo/menion.android.whereyougo.gui.activity.wherigo.ListZonesActivity} did not call through to super.onCreate()
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2913)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3032)
    at android.app.ActivityThread.-wrap11(Unknown Source:0)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1696)
    at android.os.Handler.dispatchMessage(Handler.java:105)
    at android.os.Looper.loop(Looper.java:164)
    at android.app.ActivityThread.main(ActivityThread.java:6944)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)

**Comment by Lineflyer** [comment]
Cache: All I tried
Device: Samsung S7, Android 8

User Note:
2020/03/15 21:05:02
[gui.activity.wherigo.ListThingsActivity] onCreate()
java.lang.IllegalStateException: Only fullscreen opaque activities can request orientation
at android.app.Activity.onCreate(Activity.java:1038)
at android.support.v4.app.SupportActivity.onCreate(ComponentActivity.java:75)
at android.support.v4.app.FragmentActivity.onCreate(FragmentActivity.java:335)
at menion.android.whereyougo.gui.extension.activity.CustomActivity.onCreate(CustomActivity.java:161)
at menion.android.whereyougo.gui.activity.wherigo.ListVariousActivity.onCreate(ListVariousActivity.java:176)
at menion.android.whereyougo.gui.activity.wherigo.ListThingsActivity.onCreate(ListThingsActivity.java:71)
at android.app.Activity.performCreate(Activity.java:7183)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1220)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2910)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3032)
at android.app.ActivityThread.-wrap11(Unknown Source:0)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1696)
at android.os.Handler.dispatchMessage(Handler.java:105)
at android.os.Looper.loop(Looper.java:164)
at android.app.ActivityThread.main(ActivityThread.java:6944)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
2020/03/15 21:05:02
[UncaughtExceptionHandler] uncaughtException main
android.util.SuperNotCalledException: Activity {menion.android.whereyougo/menion.android.whereyougo.gui.activity.wherigo.ListThingsActivity} did not call through to super.onCreate()
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2913)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3032)
at android.app.ActivityThread.-wrap11(Unknown Source:0)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1696)
at android.os.Handler.dispatchMessage(Handler.java:105)
at android.os.Looper.loop(Looper.java:164)
at android.app.ActivityThread.main(ActivityThread.java:6944)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)

**Comment by jakedot** [comment]
See #86 for another case. Closed there because it's probably duplicate.

**Comment by allyourcodearebelongtous** [comment]
There seems to be a solution on StackOverflow:

https://stackoverflow.com/questions/48072438/java-lang-illegalstateexception-only-fullscreen-opaque-activities-can-request-o

The problem seems to be happening when your target sdk is 28. So after trying out many options finally this worked.

```
<activity
            android:name=".activities.FilterActivity"
            android:theme="@style/Transparent"
            android:windowSoftInputMode="stateHidden|adjustResize" />
```
style:-

```
<style name="Transparent" parent="Theme.AppCompat.Light.NoActionBar">
     <item name="android:windowIsTranslucent">true</item>
     <item name="android:windowBackground">@android:color/transparent</item>
     <item name="android:windowIsFloating">true</item>
     <item name="android:windowContentOverlay">@null</item>
     <item name="android:windowNoTitle">true</item>
     <item name="android:backgroundDimEnabled">false</item>
 </style>
```
Note:parent="Theme.AppCompat.Light.NoActionBar" is needed for api 28. Previously had something else at api 26. Was working great but started to give problem at 28. Hope it helps someone out here. EDIT: For some only by setting <item name="android:windowIsTranslucent">false</item> and  <item name="android:windowIsFloating">false</item> worked.May be depends upon the way you implement the solution works.In my case it worked by setting them to true.

**Comment by jakedot** [comment]
>Hope it helps someone out here

Thanks a lot, I'm sure we can use this information.

**Comment by Lineflyer** [comment]
I took a look into the Google Play reporting:
The `android.util.SuperNotCalledException` occurs only on Android 8 devices (masively).

Two different stack traces are reported:
```
android.util.SuperNotCalledException: 
 
  at android.app.ActivityThread.performLaunchActivity (ActivityThread.java:2913)
 
  at android.app.ActivityThread.handleLaunchActivity (ActivityThread.java:3032)
 
  at android.app.ActivityThread.-wrap11 (Unknown Source)
 
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1696)
 
  at android.os.Handler.dispatchMessage (Handler.java:105)
 
  at android.os.Looper.loop (Looper.java:164)
 
  at android.app.ActivityThread.main (ActivityThread.java:6944)
 
  at java.lang.reflect.Method.invoke (Native Method)
 
  at com.android.internal.os.Zygote$MethodAndArgsCaller.run (Zygote.java:327)
 
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1374)
```

```
android.util.SuperNotCalledException: 
 
  at android.app.ActivityThread.performLaunchActivity (ActivityThread.java:3253)
 
  at android.app.ActivityThread.handleLaunchActivity (ActivityThread.java:3405)
 
  at android.app.ActivityThread.-wrap12 (Unknown Source)
 
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1994)
 
  at android.os.Handler.dispatchMessage (Handler.java:108)
 
  at android.os.Looper.loop (Looper.java:166)
 
  at android.app.ActivityThread.main (ActivityThread.java:7523)
 
  at java.lang.reflect.Method.invoke (Native Method)
 
  at com.android.internal.os.Zygote$MethodAndArgsCaller.run (Zygote.java:245)
 
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:921)
```

**Comment by Lineflyer** [comment]
Is anyone able to take a look into the possible solution provided by @allyourcodearebelongtous whether it can be applied to WhereYouGo?
That seems to be the major regression caused by targetSDK28 we know of.

**Comment by bekuno** [comment]
I can't.
I do not own a suitable testenvironment.

**Comment by allyourcodearebelongtous** [comment]
Maybe you could try the following fix (which is described by Ragesh Ramesh on January, 3rd, 18 in StackOverflow just below the fix I mentioned) and test it on Android 9. 

If all works well this could be published to Google Play as a beta version which I could test against Android 8. I registered as beta tester for WhereYouGo, so I could update and test it on my device. WhereYouGo 2020.03.08 is broken on my device, anyway.

Here is the link again: https://stackoverflow.com/questions/48072438/java-lang-illegalstateexception-only-fullscreen-opaque-activities-can-request-o

> In Android O and later this error happens when you set
> 
>  android:screenOrientation="portrait"
> in Manifest.
> 
> Remove that line and use
> 
>  setRequestedOrientation(ActivityInfo.SCREEN_ORIENTATION_PORTRAIT);
> in your activity.
> 
> This will fix your issue.
> 

Manifest looks like it could work:

> $ grep -R android:screenOrientation *
> src/main/AndroidManifest.xml:            android:screenOrientation="portrait">
> src/main/AndroidManifest.xml:            android:screenOrientation="portrait" />
> src/main/AndroidManifest.xml:            android:screenOrientation="portrait" />
> src/main/AndroidManifest.xml:            android:screenOrientation="portrait" />
> src/main/AndroidManifest.xml:            android:screenOrientation="portrait" />
> src/main/AndroidManifest.xml:            android:screenOrientation="portrait" />
> src/main/AndroidManifest.xml:            android:screenOrientation="portrait" />
> src/main/AndroidManifest.xml:            android:screenOrientation="portrait"
> src/main/AndroidManifest.xml:            android:screenOrientation="portrait"
> src/main/AndroidManifest.xml:            android:screenOrientation="portrait"
> src/main/AndroidManifest.xml:            android:screenOrientation="portrait" />
> src/main/AndroidManifest.xml:            android:screenOrientation="portrait" />
> src/main/AndroidManifest.xml:            android:screenOrientation="portrait" />
> src/main/AndroidManifest.xml:            android:screenOrientation="portrait"
> src/main/AndroidManifest.xml:            android:screenOrientation="portrait" />
> src/main/AndroidManifest.xml:            android:screenOrientation="fullSensor"
> 
> Hampf@Hampfs-PC MINGW64 ~/Documents/GitHub/WhereYouGo (master)

remove the lines with "portrait" and add

> setRequestedOrientation(ActivityInfo.SCREEN_ORIENTATION_PORTRAIT);

maybe there **(just guessing, I'm not a Android App Pro)** in "CustomActivity.java"

> protected static void setScreenBasic(Activity activity) {
>         try {
>             activity.requestWindowFeature(Window.FEATURE_NO_TITLE);
>         } catch (Exception e) {
>             // TODO Logger.e(TAG, "setFullScreen(" + activity + ")", e);
>         }
>     }

And keep your fingers crossed.

Cheers,
Hampf

**Comment by allyourcodearebelongtous** [comment]
...and I suppose above should read:

```
protected static void setScreenBasic(Activity activity) {
   try { 
      activity.requestWindowFeature(Window.FEATURE_NO_TITLE);
      activity.setRequestedOrientation(ActivityInfo.SCREEN_ORIENTATION_PORTRAIT);
   } catch (Exception e) {
      // TODO Logger.e(TAG, "setFullScreen(" + activity + ")", e);
   }
}
```
to be functional in all ...Activity classes, because all of them inherit from CustomActivity

**Comment by bekuno** [comment]
@allyourcodearebelongtous 
I merged now the migrated code for AndroidX.
Please test, if the problem occures.
You find the apk at https://ci.cgeo.org/view/WhereYouGo/job/whereyougo%20(nightly)/lastSuccessfulBuild/artifact/build/outputs/apk/nightly/whereyougo-2020.03.29-NB-3f6e4c3.apk

**Comment by allyourcodearebelongtous** [comment]
Well, it installed OK, but unluckily still fails with same stacktrace.
I'll try and download Android Studio, maybe I can try and find the error by myself. But don't have high hopes.
Is the nightly build available on GitHub?

**Comment by bekuno** [comment]
>Is the nightly build available on GitHub?

You can take them directly from CI at https://ci.cgeo.org/view/WhereYouGo/job/whereyougo%20(nightly)/ .

**Comment by bekuno** [comment]
> I'll try and download Android Studio, maybe I can try and find the error by myself. But don't have high hopes.

Every small help is fine.

**Comment by allyourcodearebelongtous** [comment]
Bad thing: it took nearly an eternity to install and use Android Studio, BUT:
I succeeded in building WhereYouGo APK files, modified, uploaded and tested the endless modifications one by one. At last following solution worked (for me):

In AndroidManifest.sml replace "portrait" in the corresponding following lines with "fullSensor". I don't know whether the other manifest lines containing "portrait" should be changed as well. I left them unchanged.

        <activity
            android:name="menion.android.whereyougo.gui.activity.wherigo.ListActionsActivity"
            android:screenOrientation="fullSensor" />
        <activity
            android:name="menion.android.whereyougo.gui.activity.wherigo.ListTargetsActivity"
            android:screenOrientation="fullSensor" />
        <activity
            android:name="menion.android.whereyougo.gui.activity.wherigo.ListTasksActivity"
            android:screenOrientation="fullSensor"
            android:theme="@android:style/Theme.Dialog" />
        <activity
            android:name="menion.android.whereyougo.gui.activity.wherigo.ListThingsActivity"
            android:screenOrientation="fullSensor"
            android:theme="@android:style/Theme.Dialog" />
        <activity
            android:name="menion.android.whereyougo.gui.activity.wherigo.ListZonesActivity"
            android:screenOrientation="fullSensor"
            android:theme="@android:style/Theme.Dialog" />

Nun habe ich allerdings ein anderes Problem: beim Speichern kommt eine NullPointerException und die Cartridge beginnt quasi von Anfang an. Das sollte aber bei Bedarf ein neues Issue werden.

So long,
Hampf (allyourcodearebelongtous)

**Comment by allyourcodearebelongtous** [comment]
addendum: I don't want to receive all the kudos for this. I found the solution here:
https://stackoverflow.com/questions/3260576/error-in-android-supernotcalledexceptionactivity-did-not-call-through-to-super

**Comment by bekuno** [comment]
> Bad thing: it took nearly an eternity to install and use Android Studio, BUT:

You can follow the c:geo AS installation instruction at https://github.com/cgeo/cgeo/wiki/Android-Studio . And then clone your WhereYouGo repo (should a clone from cgeo\WhereYouGo).
Additionally you need to install the NDK.

**Comment by allyourcodearebelongtous** [comment]
Thanks for pointing me to that. 
I hope the solution works for A9 as well. 

Am 29. März 2020 22:16:50 MESZ schrieb Bernd <notifications@github.com>:

**Comment by allyourcodearebelongtous** [comment]
I had to import Android API level 28 via "Tools->SDK Manager" as well. Android Studio actually comes preinstalled with Android 10 (level 29) only. After that I did "File->Invalidate Caches / Restart..."
Android Studio marks the lines containing "portrait" in AndroidManifest.xml as follows:
![2020-03-30 12_29_42-WhereYouGo  C__Users_h vogt-ostmann_StudioProjects_WhereYouGo  -  _src_main_An](https://user-images.githubusercontent.com/46929603/77903049-84f22c80-7282-11ea-9491-bcc748066a0c.png)
I now changed them ALL to "fullSensor" and was able to complete a Wherigo with all its features without any problems.
So 
`android:screenOrientation="fullSensor" `
did the trick.

**Comment by bekuno** [comment]
These Infos comes from the internal android java lint.
Mostly it is helpfull.

The screenOrientation was set to portrait from the author with intention - that it works only in this mode. After switch to fullSensor the app tries to work also in landscape.
This meens that you have to test if/how the app is playable in landscape mode. Maybe you have also a tablet or can configure a virtual device to test the behavior.

I tried some of the ideas to set the orientation programmativly to portrait. But this was not fine. Abter turning the smartphone in landscape mode and the hit "map" it starts the activity at first in landscape mode and then switched it to portrait. 

So we have to possibilities: Test and support using the app completely in landcape mode or find a way to  fix the orientation in portrait mode.

By the way, I tested with android 9. There is no problem with the original code.

**Comment by bekuno** [comment]
> I had to import Android API level 28 via "Tools->SDK Manager" as well. Android Studio actually comes

You need all levels depending of you hardware or virtual device.

**Comment by allyourcodearebelongtous** [comment]
I just finished testing the same Wherigo completely in landscape mode. No problems, everything worked like a charm.
Samsung Galaxy S7
Android 8.0

**Comment by bekuno** [comment]
@allyourcodearebelongtous Do you want to create your own PR for this?

@Lineflyer I think we could try to remove the landscape mode restriction from WhereYouGo. User can fix their smartphone to portrait mode by the system configuration, if necessary. What do you mean?

**Comment by Lineflyer** [comment]
> @Lineflyer I think we could try to remove the landscape mode restriction from WhereYouGo. User can fix their smartphone to portrait mode by the system configuration, if necessary. What do you mean?

I have no idea what happens if you play a cartridge in landscape...
How about keeping the changes to a minimum for now to just get it working as before on Android 8. (Sorry, I was not able to follow this discussion completely)?

**Comment by bekuno** [comment]
>(Sorry, I was not able to follow this discussion completely)?

In short: There is a bug only in android8 when defining portrait mode in AndroidManifest.xml. All solutions I found did not work fine as substitute.
 
> How about keeping the changes to a minimum for now to just get it working as before on Android 8.

If we only partially remove the portrait mode then users can be really confused when only some activities are flip between landscape and portrait mode.

**Comment by allyourcodearebelongtous** [comment]
I finally succeeded in creating a PR.
Does it get linked to this issue automatically or do you have to make a connection manually when merging the commit?
